kind: pipeline
type: docker
name: build

trigger:
  event:
    - push

steps:
  - name: build
    image: golang:alpine
    commands:
      - ls
      - go build .
      - ls
    when:
      branch:
        - master
